### ISSUE TITLE
Ma vai a fanculo.

### ISSUE THREAD

**Issue by LichareKEK** [SamuelPozzobon/ParcheggiatoreAbusivoSoftware#1]
Mia mamma è dei carabinieri e essendo questo un programma a fini illeciti le riporterò questo caso. Il tuo nome e cognome sono presenti nel tuo username. Buona serata.

**Comment by SamuelPozzobon** [comment]
Mi segnali anche SpesaCalculator2000 allora, visto che puoi calcolare il valore dei tuoi reni!
